intt = int(input("İnteger bir değer giriniz: "))
strr = input("String bir değer giriniz: ")
floatt = float(input("Float bir değer giriniz: "))
d = input("Bir değer giriniz: ")
e = input("Bir değer giriniz: ")
print(intt)
print(strr)
print(floatt)
print(d)
print(e)
print("intt değişkeninin tipi {}".format(type(intt)))
print("strr değişkeninin tipi {}".format(type(strr)))
print("floatt değişkeninin tipi {}".format(type(floatt)))
print(f"d değişkeninin tipi {type(d)}")
print(f"e değişkeninin tipi {type(e)}")
